Infineon/arduino-core-psoc6

cores/psoc/main.cpp, platform.txt, tools/mtb_build_info.py
⚠️ !!
Review after #10, as this is derived from the sketch-upload branch.
* Added cmd to mtb_build_info script to get the include dirs and modify to right path for platform.txt
* Added include dir from mtb + proper linkage of mtb-libs.a lib in platform.txt
* Included dummy hello world in cores/psoc/main.cpp
=> Missing mtb includes

docs/development-instructions.rst, docs/hw-platforms.rst, docs/index.rst, docs/installation-instructions.rst
=> docs: Added work in progress notice.

CODE_OF_CONDUCT.md
Description
Related Issue
Context
=> CODE_OF_CONDUCT.md: Add covenant code of conduct.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.md, .github/ISSUE_TEMPLATE/feature_request.md
Description
Related Issue
Context
=> .github/ISSUE_TEMPLATE: Add bug report and feature request templates.

docs/index.rst, docs/supported-features.rst
https://arduino-core-psoc.readthedocs.io/en/add-supported-feature-list/supported-features.html#built-in-libraries
=> Add supported features list to the docs

CODE_CONVENTIONS.md, cores/psoc/Uart.h
Fixing format due to uncrustify versions.
=> cores/psoc/Uart.h: Fixed pointer format.

tests/cy8ckit-062s2-ai-hil-test-table.md
HIL setup connection Table
Here also the codeformatting is failing but locally codeformatting is passing.  I tried the suggested changes but then pre commit hook is changing that.
=> tests: HIL Setup connection table.

.github/workflows/hil_unity_checks.yml
=> .github/workflows/hil_unity_checks.yml: Updated arduino-devops scripts.

cores/psoc/digital_io.c, cores/psoc/interrupts.c, variants/CY8CKIT-062S2-AI/pins_arduino.h
Description
Related Issue
Context
=> cores/psoc: variants/CY8CKIT-062S2-AI: Fix warnings.

libraries/WiFi/src/WiFi.cpp, libraries/WiFi/src/WiFi.h, platform.txt
Review only after #52 ⚠️ 
* Added status() and localIP() functions.
* Added basic tests for these functions. 
* Configure singleton for either Station or Access Point mode.
=> Wifi net status localip

cores/psoc/time.c, libraries/WiFi/src/Socket.cpp, libraries/WiFi/src/Socket.h, libraries/WiFi/src/WiFiClient.cpp, libraries/WiFi/src/WiFiClient.h, libraries/WiFi/src/WiFiServer.cpp, libraries/WiFi/src/WiFiServer.h, platform.txt
* Added WiFiClass and begin() implementation.  Empty functions required by pure virtual interfaces inherited.
* Added WiFiClient and connect() implementation.  Empty functions required by pure virtual interfaces inherited.
* Added Socket class wrapping the secure_socket C MTB library. This will be used by both client and server classes. 
* Updated reference to added client and server tests in arduino-core-tests.
* Added new mtb-libs.a with secure socket component (updated reference to extras/mtb-integration)
* Implemented delay timing functions …
=> Wifi client server basic connection

libraries/WiFi/src/Socket.cpp, libraries/WiFi/src/Socket.h, libraries/WiFi/src/WiFiClient.cpp, libraries/WiFi/src/WiFiClient.h, libraries/WiFi/src/WiFiServer.cpp, libraries/WiFi/src/WiFiServer.h
To be reviewed after #55 ⚠️ 
* Added status and error tracking to Socket class. Required for handling the status in WiFiServer and WiFiClient.
* Added client.connected() based on Socket.status()
* Added client bool operator based on client is connected, and client has data available (still not implemented). This is required by the WiFiServer class.
* Added server.available()
=> Wifi client connected server available

libraries/WiFi/src/Socket.cpp, libraries/WiFi/src/Socket.h, libraries/WiFi/src/WiFiClient.cpp, libraries/WiFi/src/WiFiClient.h, libraries/WiFi/src/WiFiServer.cpp, libraries/WiFi/src/WiFiServer.h
Completion of WiFiServer and WiFiClient classes (except secure SSL functions):
* Server & Client: Added disconnect callbacks.
* Client: Added functions connect(byhost), remoteIP(), remotePort(), flush(), peek(), print(), println(), copy constructor and assignment operator.
* Server: write(), print(), println(), bool operator, status(). Several implementation improvements on connected_clients handling. 
* Other minor refactors: variables and function renaming, etc.
Tests in this PR: https://github.com/Infineon/arduino-core-tests/pull/13
=> Wifi server client remaining

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, README.md, tools/dev-setup.cmd, tools/dev-setup.sh, tools/mtb-lib.cmd
1. Contributors list extended
2.  Fix issue with bug report template
3. Fix windows build issue
=> Fix compile issue windows

tools/dev-setup.cmd, tools/dev-setup.sh
=> tools/dev-setup.*: Documented workaround and linked related issue.

ci-build-matrix.json
Adding windows to compile-example check.
=> ci-build-matrix.json: Added OSs as part of the matrix json.

ci-build-matrix.json, libraries/WiFi/examples/ConnectNoEncryption/ConnectNoEncryption.ino, libraries/WiFi/examples/ConnectNoEncryption/secrets.h, libraries/WiFi/examples/ConnectWithWPA/ConnectWithWPA.ino, libraries/WiFi/examples/ConnectWithWPA/secrets.h, libraries/WiFi/examples/SimpleWebServerWiFi/SimpleWebServerWiFi.ino, libraries/WiFi/examples/SimpleWebServerWiFi/secrets.h, libraries/WiFi/examples/WiFiWebClient/WiFiWebClient.ino, libraries/WiFi/examples/WiFiWebClient/secrets.h, libraries/WiFi/src/WiFi.h, variants/CY8CKIT-062S2-AI/lwipopts.h
Description
Related Issue
Context
=> Wifi extra fixes

libraries/SPI/keywords.txt, libraries/SPI/library.properties, libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h, libraries/WiFi/src/SecSocket.cpp, libraries/WiFi/src/WiFi.cpp, libraries/WiFi/src/WiFiClient.cpp, libraries/WiFi/src/WiFiServer.cpp, libraries/Wire/Wire.cpp, libraries/Wire/library.properties, tools/codeformat.py, variants/CY8CKIT-062S2-AI/pins_arduino.h
SPI master implementation without interrupts.
https://github.com/Infineon/arduino-core-tests/blob/add-spi-test-transfer/src/corelibs/spi/test_spi_connected1_loopback.cpp
=> libraries/SPI: Add implementation for SPI interface.

libraries/WiFi/examples/WiFiPing/WiFiPing.ino, libraries/WiFi/examples/WiFiPing/secrets.h, libraries/WiFi/src/WiFi.cpp, libraries/WiFi/src/WiFi.h
To be reviewed after #78.
The WiFi.ping() returns and arguments differ for each core. 
It can be extended with more error codes, and providing the timeout configurability and time elapsed return from the wcm API ping() function. For now it just return success or fail, and has a hardcoded timeout of 10 seconds.
Tests --> 
https://github.com/Infineon/arduino-core-tests/pull/21
=> WiFi library: Added WiFi.ping() function.

libraries/WiFi/src/WiFi.cpp, libraries/WiFi/src/WiFi.h
To be reviewed after #82.
* Added config() and dnsIP() functions
Related tests: https://github.com/Infineon/arduino-core-tests/pull/23
=> WiFi library: Added config() and dnsIP() functions.

cores/psoc6/digital_io.c, libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h, tests/cy8ckit-062s2-ai-hil-test-table.md, tests/test_config.h, variants/CY8CKIT-062S2-AI/pins_arduino.h
SPI slave mode is also implemented.
Fixed some issues discovered when testing master slave pingpong tests.
Check the respective tests here: https://github.com/Infineon/arduino-core-tests/pull/24
=> Psoc ino spi master slave pingpong test

ci-build-matrix.json
Added SPI examples to CI compile-examples.
=> Added SPI examples to ci.

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
=> Wire refactor ringbuf latest

libraries/Wire/examples/slave_receiver/slave_receiver.ino, libraries/Wire/examples/slave_sender/slave_sender.ino, libraries/Wire/library.properties
=> libraries/Wire: Commented out delays on examples. Bumped lib version.

platform.txt
=> platform.txt: Bumped version to 0.2.0.

platform.txt, variants/CY8CKIT-062S2-AI/pins_arduino.h
=> variants/CY8CKIT-062-S2/pins_arduino.h: Fixed default SPI pins.

libraries/WiFi/src/WiFi.cpp, libraries/WiFi/src/WiFi.h
=> Wifi reason code

libraries/WiFi/src/WiFi.cpp, libraries/WiFi/src/WiFi.h
WiFi Channel Function together with test
=> Wifi channel

cores/psoc6/Arduino.h, cores/psoc6/analog_io.c, docs/arduino-deviations.rst, docs/index.rst, tests/cy8ckit-062s2-ai-hil-test-table.md, tests/test_config.h, variants/CY8CKIT-062S2-AI/pins_arduino.h
ADC APIs implemented
Tests can be found here https://github.com/Infineon/arduino-core-tests/pull/33
=> Psoc ino adc

ci-build-matrix.json, cores/psoc6/analog_io.c
While rebasing the analog_io implementation got deleted by mistake. Adding the implementation back again from psoc-ino-adc back. 
Also now adding analog example to compile list.
=> Psoc ino adc fix

platform.txt
=> platform.txt: Bumped version for 0.3.0 release.

ci-build-matrix.json, package/package_psoc6_index.template.json, platform.txt
* Added macosx support by providing mtb-gcc compiler
* Added macosx support setting default recipes (for linux and macosx)
* Added macosx to ci matrix configuration file
=> Enablement of Mac OS X 

platform.txt
=> platform.txt: Bumped version to 0.5.0.

libraries/WiFi/src/WiFiUdp.cpp
=> Wi fi udp stop

README.md
=> README.md: Fixed link to workflow.

libraries/WiFi/src/WiFiUdp.cpp, libraries/WiFi/src/WiFiUdp.h
Writes UDP data to the remote connection. Must be wrapped between beginPacket() and endPacket(). beginPacket() initializes the packet of data, it is not sent until endPacket() is called.
=>  libraries/WiFi: Write function.

libraries/WiFi/src/SecSocket.cpp, libraries/WiFi/src/SecSocket.h, libraries/WiFi/src/WiFiUdp.cpp
WiFiUDP.endPacket() - Called after writing UDP data to the remote connection. It finishes off the packet and send it
Modified the socket.send function to have the corresponding cyhal function for UDP data
=> Wi fi udp endpacket

.gitmodules, tests/test_config.h
update core test submodule here
+ 
adding makers-devops as submodule which will be used to run HIL tests locally as well as on CI/CD
=> Update core test submodule

libraries/WiFi/src/SecSocket.cpp, libraries/WiFi/src/SecSocket.h, libraries/WiFi/src/WiFiUdp.cpp, libraries/WiFi/src/WiFiUdp.h
Implementation of the following functions
- ParsePacket
- Read
- Peek
- Flush
- RemoteIP
- RemotePort
- Callback function modification in securesocket.cpp to support UDP
- Code cleanup
- Testing done for above functions
=> WiFi UDP Recieve functions

libraries/WiFi/examples/WiFiUdpNtpClient/WiFiUdpNtpClient.ino, libraries/WiFi/examples/WiFiUdpNtpClient/secrets.h, libraries/WiFi/examples/WiFiUdpReceiver/WiFiUdpReceiver.ino, libraries/WiFi/examples/WiFiUdpReceiver/secrets.h, libraries/WiFi/examples/WiFiUdpSender/WiFiUdpSender.ino, libraries/WiFi/examples/WiFiUdpSender/secrets.h
=>  libraries/WiFi: Add UDP Examples.

libraries/WiFi/keywords.txt, libraries/WiFi/library.properties, package/config.yml, platform.txt
=> Minor updates in metafiles

variants/CY8CKIT-062S2-AI/pins_arduino.h
=> variants/CY8CKIT-062S2-AI/pins_arduino.h: Added internal pin mapping.

README.md
This pull request updates the `README.md` file to improve the documentation by replacing the image source for the CY8CKIT-062S2-AI board with a local file path.
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L49-R49): Changed the image source for the CY8CKIT-062S2-AI board from a URL to a local file path (`docs/img/board_CY8CKIT-062S2-AI.png`) to ensure consistent rendering and reduce dependency on external links.
=> README.md: Fix picture link.

cores/psoc6/Random.cpp, docs/arduino-deviations.rst, docs/supported-features.rst
Generate RNG based on TRNG from cyhal.
Tests can be found: 
https://github.com/Infineon/arduino-core-tests/pull/50
=> Psoc ino random

cores/psoc6/Arduino.h, cores/psoc6/digital_io.c, variants/CY8CKIT-062S2-AI/pins_arduino.h
A tracking array that records the initialisation status of each GPIO pin, ensuring that a pin is properly freed before any attempt to reinitialise it.
=> Gpio reinit fix

.github/workflows/code_checks.yml, .pre-commit-config.yaml, config/project.yml, config/user.yml, cores/psoc6/Pulse.cpp, cores/psoc6/Random.cpp, cores/psoc6/Tone.cpp, cores/psoc6/Uart.h, cores/psoc6/main.cpp, cores/psoc6/time.c, libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h, libraries/WiFi/src/SecSocket.cpp, libraries/WiFi/src/SecSocket.h, libraries/WiFi/src/WiFi.cpp, libraries/WiFi/src/WiFi.h, libraries/WiFi/src/WiFiClient.cpp, libraries/WiFi/src/WiFiClient.h, libraries/WiFi/src/WiFiServer.cpp, libraries/WiFi/src/WiFiServer.h, libraries/WiFi/src/WiFiUdp.h, libraries/Wire/src/Wire.h
fix clang tidy warnings.
https://infineon.github.io/arduino-core-psoc6/
=> Fix clang tidy warnings1

config/project.yml, config/user.yml, tests/cy8ckit-062s2-ai-hil-test-table.md
Description
Related Issue
Context
=> Onewire unit test hil
