.gitmodules
README.md
docs/conf.py
docs/development-instructions.rst
docs/index.rst
docs/installation-instructions.rst
tools/dev-setup.sh

* Added coreAPI as a submodule
* Added tools/dev-setup.sh script which currently: 
- updates git submodules 
- create symlink folder in cores/psoc of the /api folder
* Updated documentation for installation instruction (assuming existing first package installable via JSON). --> 
- https://arduino-core-psoc.readthedocs.io/en/api-setup/development-instructions.html
- https://arduino-core-psoc.readthedocs.io/en/api-setup/installation-instructions.html#installation-in-arduino-cli

Created development setup script (including docs)

---

docs/development-instructions.rst

Added manual symlink for windows:
https://arduino-core-psoc.readthedocs.io/en/docs-win-symlink/development-instructions.html#installing-the-arduinocore-api

docs/development-instructions.rst: Added symlink creation for Windows.

---

.gitignore
boards.txt
platform.txt

* Added **_upload_ command** based on openocd tool.
* The right port will be selected for flashing when multiple Kitprog3 devices are connected 😃.
* The --verbose option will print the -debug level mode 2 (default) openocd flashing progress.
* The --quiet (default) option log the output in a file in the build temp folder.
**Instructions to test** (so far I have only done in the arduino-cli wsl)
- Make sure the udev_rules are enabled: ~/.arduino15/packages/Infineon-psoc/tools/ModusToolbox/tools_3.2/fw-loader/udev_rules/install_rules.sh
For an "example/example.ino" file:
- `arduino-cli compile --clean -b Infineon-psoc:psoc:CY8CKIT-062S2-AI-Kit ./example/example.ino`
- `arduino-cli upload --fqbn Infineon-psoc:psoc:CY8CKIT-062S2-AI-Kit -p /dev/ttyACM0 example/example.ino [--verbose]`
**What …

Sketch upload

---

platform.txt
tools/mtb_build_info.py
tools/upload.bat
tools/upload.sh

This PR addresses the following topics:
- Path slashes issues in windows environment solved by .bat file and modifications in get_build_flags.py script (this one is anyhow to be refactor to avoid python dependency).
- Cleanup, simplified and more modular platform.txt for upload recipe.
- Bash script with the following features:
- Verbose mode: prints all arguments, command line openocd call and openocd output
- Quiet (default) mode: openocd output saved in a log file in build folder.
- help document all positional and optional arguments.
- Error parser helper to parse openocd errors into user friendly …

Upload script refactor

---

boards.txt
mtb-libs/Makefile
platform.txt

Description
Related Issue
Context

Fix code size mtb tools path

---

.github/workflows/build.yml
.gitignore
package/package_psoc_index.template.json
platform.txt
tools/release.py

Extended the workflow to host a local server and consume the package json and package folder in Arduino installation.
With this approach:
1. we could avoid consuming the packages directly from releases. 
2. we perform sanity check of the package generation and package json generation.

Remove package json consumption

---

cores/psoc/Arduino.h
cores/psoc/Uart.cpp
cores/psoc/Uart.h
cores/psoc/digital_io.c
cores/psoc/interrupts.c
cores/psoc/main.cpp
examples/blinkLEDWithInterrupt/blinkLEDWithInterrupt.ino
examples/testSketch/testSketch.ino
tests/test_config.h
variants/CY8CKIT-062S2-AI/pins_arduino.h

Implementation of GPIO interrupt.
Test can be run locally with "make FQBN=infineon:psoc:cy8ckit_062s2_ai PORT=/dev/ttyACM0 test_interrupts_single" command using the arduino-core-test branch "https://github.com/Infineon/arduino-core-tests/tree/add-gpio-interrupt-tests"
Note: Pin 7 and 6 needs to be shorted.
There are some changes in arduino-core-test which needs to be merged for digital IO hil test to pass.
Also there is an example code blinkLEDWithInterrupt.ino which blinks LED with USER BUTTON press.

Psoc ino interrupts

---

libraries/WiFi/src/Socket.cpp
libraries/WiFi/src/Socket.h
libraries/WiFi/src/WiFiClient.cpp
libraries/WiFi/src/WiFiClient.h
libraries/WiFi/src/WiFiServer.cpp
libraries/WiFi/src/WiFiServer.h

This PR enables the write() and read() function from both WiFiClient and WiFiServer. 
The relationship between server and client and how the sockets handle the reception depending on the role 
require to set a different callback depending if:
* The client instance is using connect() to connect to a server. 
* The client instance is one of the server side connected clients. 
The tests in this PR -> https://github.com/Infineon/arduino-core-tests/pull/12
Also, as required some refactors and modification on the Socket class.

Wifi client and server read and write

---

libraries/WiFi/src/SecSocket.cpp
libraries/WiFi/src/SecSocket.h
libraries/WiFi/src/WiFi.cpp
libraries/WiFi/src/WiFi.h
libraries/WiFi/src/WiFiClient.cpp
libraries/WiFi/src/WiFiServer.cpp

Completion of `WiFiClass`:
* Added functions `gatewayIP()`, `hostByName()`.
* Added wifi_status_t enum to track the WiFi instance state machine. 
- That will be used to control the validity of calls to certain functions depending on the status and the mode of the instance (station or access point).
- This will reuse some of the status used by official core WiFi libraries to maintain compatibility accross cores.
Other changes:
Renaming of public API functions in Socket to maintain the Arduino convention.

WiFi lib: Refactoring for"status" state machine. Function renaming. Added gatewayIP and hostByName().

---

.github/workflows/docs.yml

Description
This replaces the local workflow for build checking docs by a reusable workflow from makers-devops.
Merge Checklist
https://github.com/Infineon/arduino-core-psoc6/blob/643fc83415729b35bbd94934218e256f6a61bf03/.github/workflows/docs.yml#L15
Related Issue
Solving a not existing problem :)
Context
Once adapted in this repository, this will be rolled out to all other repos using Sphinx and Make for docs.
(testing this new Copilot PR summary feature)
This pull request modifies the `.github/workflows/docs.yml` file to streamline the documentation build process by reusing an existing workflow. The most …

Make docs build workflow reusable.

---

libraries/WiFi/examples/WiFiPing/WiFiPing.ino
libraries/WiFi/examples/WiFiWebClient/WiFiWebClient.ino
libraries/WiFi/src/SecSocket.h
libraries/WiFi/src/WiFi.h
libraries/WiFi/src/WiFiClient.h
libraries/WiFi/src/WiFiServer.h
platform.txt
tools/dev-setup.cmd
tools/dev-setup.sh

Removed renaming of api files. This change makes the handling of the Arduino-CoreAPI simpler and easier to maintain.
As suggested by Arduino code owners: https://github.com/arduino/ArduinoCore-API/issues/37#issuecomment-2718229952

Core api no rename for win

---

cores/psoc6/time.c
libraries/Wire/examples/slave_receiver/slave_receiver.ino
libraries/Wire/examples/slave_sender/slave_sender.ino

Reverted delay functions to original implementation. 
We used systick originally, then it was not working with wifi so we replaced it by vTaskDelay(). 
Then we refactored it based on the cyhal_timer, but keep the vTaskDelay() implementation. And that is blocking the interrupt triggering (we had this behavior in the Wire slave implementation). 
Now with the cyhal_timer implementation, the original millis()/micro() time difference works without any identified flaw.
Manually evaluated the following tests:
- test_digitalio_single
- …

cores/psoc6/time.c : Refactored delay() and delayMicroseconds() implementation.

---

cores/psoc6/Arduino.h
cores/psoc6/Uart.cpp
cores/psoc6/Uart.h
cores/psoc6/Uart0.cpp
cores/psoc6/Uart1.cpp
tests/cy8ckit-062s2-ai-hil-test-table.md
variants/CY8CKIT-062S2-AI/pins_arduino.h

This pull request refactors the UART implementation for the PSoC6 platform, improving code maintainability, flexibility, and functionality. Key changes include the introduction of hardware flow control, a new ring buffer for RX data, and enhanced error handling. Additionally, the UART pin definitions were updated for better clarity and usability.
* Replaced software buffer with `RingBuffer` for RX data, improving performance and simplifying buffer management (`cores/psoc6/Uart.cpp`, `cores/psoc6/Uart.h`). …

cores/psoc6/Uart: Fixes on tx overflow and improvements

---

ci-build-matrix.json
cores/psoc6/Arduino.h
cores/psoc6/analog_io.c
docs/arduino-deviations.rst
tests/cy8ckit-062s2-ai-hil-test-table.md
tests/test_config.h
variants/CY8CKIT-062S2-AI/pins_arduino.h

Implemented APIs :
1. AnalogWrite(pin, value);
2. AnalogWriteResolution(res);
Corresponding tests can be found at : https://github.com/Infineon/arduino-core-tests/pull/34

Psoc ino pwm

---

libraries/WiFi/src/WiFiUdp.cpp

UDP. beginPacket(IPAddress ip, uint16_t port)
UDP. beginPacket(const char *host, uint16_t port)
UDP. beginPacket(IPAddress ip, uint16_t port) is added in the testcase and since hostname resolution is tested as part of WiFi class , I have not added test for that .

Wifi udp begin packet

---

ci-matrix-config.yml
cores/psoc6/Pulse.cpp
docs/arduino-deviations.rst
tests/cy8ckit-062s2-ai-hil-test-table.md
tests/test_config.h

Implementation of following APIs:
https://docs.arduino.cc/language-reference/en/functions/advanced-io/pulseIn/
https://docs.arduino.cc/language-reference/en/functions/advanced-io/pulseInLong/
Corresponding tests: https://github.com/Infineon/arduino-core-tests/pull/47

cores/psoc6: ./docs: ./tests: Implement Pulse.

---

cores/psoc6/interrupts.c
docs/arduino-deviations.rst

Add interrupt modes LOW and HIGH mapping it to FALLING and RISING respectively.
Update arduino-deviation document accordingly

cores/psoc6: ./docs: Add interrupt modes high and low.

---

cores/psoc6/Arduino.h
cores/psoc6/digital_io.c
variants/CY8CKIT-062S2-AI/pins_arduino.h

Since the previous way of reinitialising the pin is not always needed, I refactored the code such that now
- cyhal_gpio_free is used only when the initial pin value should be changed
- chyal_gpio_reconfigure is used when there is a reconfiguration ( change in pin direction or drive) 
Now this also helps in reducing the delay that is caused while using the onewire library

Gpio reinit fix

---

.github/workflows/check_links.yml

This pull request adds a new GitHub Actions workflow to automate link checking for the repository. The workflow is triggered by various events, including pushes to key branches, pull requests, and a weekly scheduled run.
* [`.github/workflows/check_links.yml`](diffhunk://#diff-19b03a4b983670560a968c2d0685d9b461109e983518d9ddec0bf8aa92559da3R1-R17): Introduced a new workflow named "Check links" that uses a shared workflow from `Infineon/makers-devops` to verify links. It is triggered on `push` events to `master` and `main` branches, pull requests, and a scheduled cron job every Thursday at 3:30 AM UTC.

.github/workflows: Add link checker.

---

cores/psoc6/Arduino.h
cores/psoc6/analog_io.c
docs/arduino-deviations.rst

Implementation of setAnalogwriteFrequency function and documentation
Tests are also implemented

SetAnalogfrequency Function
